package request

const METHOD_GET = "GET"
const METHOD_POST = "POST"
const METHOD_PUT = "PUT"
const METHOD_PATCH = "PATCH"
const METHOD_HEAD = "HEAD"
const METHOD_OPTIONS = "OPTIONS"
const METHOD_DELETE = "DELETE"
const METHOD_CONNECT = "CONNECT"
const METHOD_TRACE = "TRACE"
